'use strict';

const DEFAULT_PULSE_PARAMS = Object.freeze({
  PULSE_ENABLED: false,
  PULSE_INTERVAL: 100,
  PULSE_STRENGTH: 0.005,
  PULSE_THRESHOLD_RATIO: 0.95,
  PULSE_MIN_AMP: 0.01,
  PULSE_MODE: 'homeostatic',
});

const DEFAULT_PHASE_ROTATION_PARAMS = Object.freeze({
  PHASE_ROTATION_ENABLED: false,
  OMEGA_A: 0.01,
  OMEGA_B: 0.011,
  PHASE_ROTATION_TARGET: 'field-and-memory',
  PHASE_ROTATION_RENORMALIZE: false,
  PHASE_ROTATION_RENORMALIZE_INTERVAL: 100,
  PHASE_ROTATION_RENORMALIZE_MAX_AMP_RATIO: 1.5,
});

const DEFAULT_MEMORY_PARAMS = Object.freeze({
  MEMORY_ENABLED: false,
  HISTORY_ALPHA: 0.04,
  MEMORY_WEIGHT: 0.12,
  MEMORY_WEIGHT_MODE: 'fixed',
  MEMORY_BLEND_VELOCITY: true,
  MEMORY_VELOCITY_WEIGHT_RATIO: 0.3,
  MEMORY_INIT_MODE: 'zero',
});

module.exports = {
  DEFAULT_MEMORY_PARAMS,
  DEFAULT_PHASE_ROTATION_PARAMS,
  DEFAULT_PULSE_PARAMS,
};
