'use strict';

const DEFAULT_PULSE_PARAMS = Object.freeze({
  PULSE_ENABLED: false,
  PULSE_INTERVAL: 100,
  PULSE_STRENGTH: 0.005,
  PULSE_THRESHOLD_RATIO: 0.95,
  PULSE_MIN_AMP: 0.01,
  PULSE_MODE: 'homeostatic',
});

const DEFAULT_MEMORY_PARAMS = Object.freeze({
  MEMORY_ENABLED: false,
  HISTORY_ALPHA: 0.04,
  MEMORY_WEIGHT: 0.12,
  MEMORY_WEIGHT_MODE: 'fixed',
  MEMORY_BLEND_VELOCITY: true,
  MEMORY_VELOCITY_WEIGHT_RATIO: 0.3,
  MEMORY_INIT_MODE: 'zero',
});

module.exports = {
  DEFAULT_MEMORY_PARAMS,
  DEFAULT_PULSE_PARAMS,
};
