'use strict';

const DEFAULT_PULSE_PARAMS = Object.freeze({
  PULSE_ENABLED: false,
  PULSE_INTERVAL: 100,
  PULSE_STRENGTH: 0.005,
  PULSE_THRESHOLD_RATIO: 0.95,
  PULSE_MIN_AMP: 0.01,
  PULSE_MODE: 'homeostatic',
});

const DEFAULT_PHASE_ROTATION_PARAMS = Object.freeze({
  PHASE_ROTATION_ENABLED: false,
  OMEGA_A: 0.01,
  OMEGA_B: 0.011,
  PHASE_ROTATION_TARGET: 'field-and-memory',
  PHASE_ROTATION_RENORMALIZE: false,
  PHASE_ROTATION_RENORMALIZE_INTERVAL: 100,
  PHASE_ROTATION_RENORMALIZE_MAX_AMP_RATIO: 1.5,
});

const DEFAULT_COUPLING_PARAMS = Object.freeze({
  COUPLING_ENABLED: true,
  COUPLING_TYPE: 'amplitude',
  COUPLING_G: 0.05,
  MEMORY_COUPLING_ENABLED: false,
  MEMORY_COUPLING_WEIGHT: 1.0,
  MEMORY_COUPLING_USE_BIDIRECTIONAL: true,
  MEMORY_COUPLING_MIN_AMP: 0.01,
  MEMORY_COUPLING_MODE: 'toward-other-memory',
});

const DEFAULT_PHEROMONE_PARAMS = Object.freeze({
  PHEROMONE_ENABLED: false,
  PHEROMONE_UPDATE_INTERVAL: 10,
  PHEROMONE_RETENTION: 0.99005,
  PHEROMONE_DEPOSIT: 0.01,
  PHEROMONE_DEPOSIT_THRESHOLD_RATIO: 0.7,
  PHEROMONE_DIFFUSION: 0.001,
  PHEROMONE_FEEDBACK_ENABLED: false,
  PHEROMONE_FEEDBACK_STRENGTH: 0.002,
  PHEROMONE_MAX_VALUE: 10.0,
});

const DEFAULT_MEMORY_PARAMS = Object.freeze({
  MEMORY_ENABLED: false,
  HISTORY_ALPHA: 0.04,
  MEMORY_WEIGHT: 0.12,
  MEMORY_WEIGHT_MODE: 'fixed',
  MEMORY_BLEND_VELOCITY: true,
  MEMORY_VELOCITY_WEIGHT_RATIO: 0.3,
  MEMORY_INIT_MODE: 'zero',
});

module.exports = {
  DEFAULT_COUPLING_PARAMS,
  DEFAULT_MEMORY_PARAMS,
  DEFAULT_PHASE_ROTATION_PARAMS,
  DEFAULT_PHEROMONE_PARAMS,
  DEFAULT_PULSE_PARAMS,
};
